version: 3.7.3.{build}

image:
- Visual Studio 2017
- Visual Studio 2015

configuration:
- mono
- net35
- net40
- net45
- net46
- net462

platform: Any CPU

matrix:
  exclude:
    - configuration: net35
      image: Visual Studio 2017

clone_depth: 5

before_build:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  project: Sources/Accord.NET.sln
  parallel: true
  verbosity: normal
  
test:
  assemblies:
    only:
    - '**\Accord.Tests.*.dll'
  categories:
    except:
    - Office
    - Random
    
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/322469abaeff8aca5bc9
  method: POST
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true